//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSuDungDV
    {
        public int IdSDDV { get; set; }
        public int IdDV { get; set; }
        public Nullable<decimal> GiaDV { get; set; }
        public Nullable<int> SoLuongDV { get; set; }
    
        public virtual SuDungDichVu SuDungDichVu { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
