//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CoSoDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoSoDichVu()
        {
            this.DichVus = new HashSet<DichVu>();
            this.GiayPhepCSDVs = new HashSet<GiayPhepCSDV>();
            this.LePhis = new HashSet<LePhi>();
            this.SuDungDichVus = new HashSet<SuDungDichVu>();
        }
    
        public int IdNCC { get; set; }
        [Display(Name = "Nhập tên nhà cung cấp")]
        [Required(ErrorMessage = "Không được bỏ trống {0}")]
       
        public string TenNCC { get; set; }
        [Display(Name = "Nhập tài khoản")]
        [Required(ErrorMessage = "Không được bỏ trống {0}")]
        public string TenTK { get; set; }

        [Display(Name = "Nhập địa chỉ")]
        [Required(ErrorMessage = "Không được bỏ trống {0}")]
        public string DiaChi { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayDangKi { get; set; }
        public string ImageNCC { get; set; }

        public Nullable<bool> Status { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống {0}")]
        [Display(Name = "Mật khẩu")]
        [StringLength(20, ErrorMessage = "Mật khẩu phải dài từ 3 đến 20 ký tự", MinimumLength = 3)]
        public string MatKhau { get; set; }
        [Display(Name = "Xác nhận mật khẩu")]
        [Required(ErrorMessage = "Xác nhận Mật khẩu là bắt buộc")]
        [StringLength(20, ErrorMessage = "Xác nhận mật khẩu phải dài từ 3 đến 20 ký tự", MinimumLength = 3)]
        [Compare("MatKhau", ErrorMessage = "Xác nhận mật khẩu và Mật khẩu không khớp")]
        public string ConfirmMK { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu> DichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiayPhepCSDV> GiayPhepCSDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LePhi> LePhis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuDungDichVu> SuDungDichVus { get; set; }
        [NotMapped]
        public List<CoSoDichVu> CategoryCSDV { get; set; }

    }
}
