//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LePhi
    {
        public int IdLP { get; set; }
        public Nullable<int> IdNCC { get; set; }
        public Nullable<System.DateTime> ThoiGianNop { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual CoSoDichVu CoSoDichVu { get; set; }
    }
}
