//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuDungDichVu()
        {
            this.ChiTietSuDungDVs = new HashSet<ChiTietSuDungDV>();
        }
    
        public int IdSDDV { get; set; }
        public string TenTK { get; set; }
        public Nullable<System.DateTime> ThoiGianDat { get; set; }
        public Nullable<int> IdNCC { get; set; }
        public string DiaChiDat { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSuDungDV> ChiTietSuDungDVs { get; set; }
        public virtual CoSoDichVu CoSoDichVu { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
