//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.CoSoDichVus = new HashSet<CoSoDichVu>();
            this.SuDungDichVus = new HashSet<SuDungDichVu>();
        }

        public int Id { get; set; }

        [StringLength(20)]
        [Display(Name = "Tên đăng nhập")]
        [Required(ErrorMessage = "Không được bỏ trống {0}")]
        public string TenTK { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống {0}")]
        [Display(Name = "Mật khẩu")]
        [StringLength(20, ErrorMessage = "Mật khẩu phải dài từ 6 đến 20 ký tự", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string MatKhau { get; set; }

        [StringLength(50)]
        [Display(Name = "Họ và tên")]
        [Required(ErrorMessage = "Không được bỏ trống {0}")]
        public string HoTen { get; set; }

        //[Column(TypeName = "date")]
        [Display(Name = "Ngày sinh")]
        [DataType(DataType.Date)]
        //[Required(ErrorMessage = "Không được bỏ trống {0}")]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống {0}")]
        [StringLength(11)]
        [Display(Name = "Số điện thoại")]
        public string SoDienThoai { get; set; }

        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        [Required(ErrorMessage = "Vui lòng nhập email")]
        public string Email { get; set; }

        [Display(Name = "Xác nhận mật khẩu")]
        [Required(ErrorMessage = "Xác nhận Mật khẩu là bắt buộc")]
        [StringLength(20, ErrorMessage = "Xác nhận mật khẩu phải dài từ 6 đến 20 ký tự", MinimumLength = 6)]
        [Compare("MatKhau", ErrorMessage = "Xác nhận mật khẩu và Mật khẩu không khớp")]
        public string XacNhanMK { get; set; }

        //[Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }
        public Nullable<bool> Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSoDichVu> CoSoDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuDungDichVu> SuDungDichVus { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
